// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.1
// source: chainedbft.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgType int32

const (
	MsgType_NEW_VIEW     MsgType = 0
	MsgType_NEW_PROPOSAL MsgType = 1
	MsgType_VOTE         MsgType = 2
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "NEW_VIEW",
		1: "NEW_PROPOSAL",
		2: "VOTE",
	}
	MsgType_value = map[string]int32{
		"NEW_VIEW":     0,
		"NEW_PROPOSAL": 1,
		"VOTE":         2,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_chainedbft_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_chainedbft_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_chainedbft_proto_rawDescGZIP(), []int{0}
}

type QuorumCertSignature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address   string `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	PublicKey string `protobuf:"bytes,2,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	Sig       []byte `protobuf:"bytes,3,opt,name=Sig,proto3" json:"Sig,omitempty"`
}

func (x *QuorumCertSignature) Reset() {
	*x = QuorumCertSignature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chainedbft_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuorumCertSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuorumCertSignature) ProtoMessage() {}

func (x *QuorumCertSignature) ProtoReflect() protoreflect.Message {
	mi := &file_chainedbft_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuorumCertSignature.ProtoReflect.Descriptor instead.
func (*QuorumCertSignature) Descriptor() ([]byte, []int) {
	return file_chainedbft_proto_rawDescGZIP(), []int{0}
}

func (x *QuorumCertSignature) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *QuorumCertSignature) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *QuorumCertSignature) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type ProposalMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProposalView int64                `protobuf:"varint,1,opt,name=proposalView,proto3" json:"proposalView,omitempty"`
	ProposalId   []byte               `protobuf:"bytes,2,opt,name=proposalId,proto3" json:"proposalId,omitempty"`
	Timestamp    int64                `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	JustifyQC    []byte               `protobuf:"bytes,4,opt,name=JustifyQC,proto3" json:"JustifyQC,omitempty"`
	Sig          *QuorumCertSignature `protobuf:"bytes,5,opt,name=Sig,proto3" json:"Sig,omitempty"`
	MsgDigest    []byte               `protobuf:"bytes,6,opt,name=MsgDigest,proto3" json:"MsgDigest,omitempty"`
}

func (x *ProposalMsg) Reset() {
	*x = ProposalMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chainedbft_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProposalMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalMsg) ProtoMessage() {}

func (x *ProposalMsg) ProtoReflect() protoreflect.Message {
	mi := &file_chainedbft_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalMsg.ProtoReflect.Descriptor instead.
func (*ProposalMsg) Descriptor() ([]byte, []int) {
	return file_chainedbft_proto_rawDescGZIP(), []int{1}
}

func (x *ProposalMsg) GetProposalView() int64 {
	if x != nil {
		return x.ProposalView
	}
	return 0
}

func (x *ProposalMsg) GetProposalId() []byte {
	if x != nil {
		return x.ProposalId
	}
	return nil
}

func (x *ProposalMsg) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ProposalMsg) GetJustifyQC() []byte {
	if x != nil {
		return x.JustifyQC
	}
	return nil
}

func (x *ProposalMsg) GetSig() *QuorumCertSignature {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *ProposalMsg) GetMsgDigest() []byte {
	if x != nil {
		return x.MsgDigest
	}
	return nil
}

type VoteMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VoteInfo         []byte                 `protobuf:"bytes,1,opt,name=VoteInfo,proto3" json:"VoteInfo,omitempty"`
	LedgerCommitInfo []byte                 `protobuf:"bytes,2,opt,name=LedgerCommitInfo,proto3" json:"LedgerCommitInfo,omitempty"`
	Sigs             []*QuorumCertSignature `protobuf:"bytes,3,rep,name=sigs,proto3" json:"sigs,omitempty"`
}

func (x *VoteMsg) Reset() {
	*x = VoteMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chainedbft_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoteMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteMsg) ProtoMessage() {}

func (x *VoteMsg) ProtoReflect() protoreflect.Message {
	mi := &file_chainedbft_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteMsg.ProtoReflect.Descriptor instead.
func (*VoteMsg) Descriptor() ([]byte, []int) {
	return file_chainedbft_proto_rawDescGZIP(), []int{2}
}

func (x *VoteMsg) GetVoteInfo() []byte {
	if x != nil {
		return x.VoteInfo
	}
	return nil
}

func (x *VoteMsg) GetLedgerCommitInfo() []byte {
	if x != nil {
		return x.LedgerCommitInfo
	}
	return nil
}

func (x *VoteMsg) GetSigs() []*QuorumCertSignature {
	if x != nil {
		return x.Sigs
	}
	return nil
}

var File_chainedbft_proto protoreflect.FileDescriptor

var file_chainedbft_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x62, 0x66, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x62, 0x66, 0x74, 0x70, 0x62,
	0x22, 0x5f, 0x0a, 0x13, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x43, 0x65, 0x72, 0x74, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x53, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x53, 0x69,
	0x67, 0x22, 0xe0, 0x01, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x4d, 0x73,
	0x67, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x56, 0x69, 0x65,
	0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61,
	0x6c, 0x56, 0x69, 0x65, 0x77, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61,
	0x6c, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x6f,
	0x73, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x4a, 0x75, 0x73, 0x74, 0x69, 0x66, 0x79, 0x51, 0x43,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x4a, 0x75, 0x73, 0x74, 0x69, 0x66, 0x79, 0x51,
	0x43, 0x12, 0x33, 0x0a, 0x03, 0x53, 0x69, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x62, 0x66, 0x74, 0x70, 0x62, 0x2e, 0x51, 0x75,
	0x6f, 0x72, 0x75, 0x6d, 0x43, 0x65, 0x72, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x52, 0x03, 0x53, 0x69, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x73, 0x67, 0x44, 0x69, 0x67,
	0x65, 0x73, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x4d, 0x73, 0x67, 0x44, 0x69,
	0x67, 0x65, 0x73, 0x74, 0x22, 0x88, 0x01, 0x0a, 0x07, 0x56, 0x6f, 0x74, 0x65, 0x4d, 0x73, 0x67,
	0x12, 0x1a, 0x0a, 0x08, 0x56, 0x6f, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x56, 0x6f, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2a, 0x0a, 0x10,
	0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x35, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x65, 0x64,
	0x62, 0x66, 0x74, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x43, 0x65, 0x72, 0x74,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x04, 0x73, 0x69, 0x67, 0x73, 0x2a,
	0x33, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x45,
	0x57, 0x5f, 0x56, 0x49, 0x45, 0x57, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x45, 0x57, 0x5f,
	0x50, 0x52, 0x4f, 0x50, 0x4f, 0x53, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x56, 0x4f,
	0x54, 0x45, 0x10, 0x02, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_chainedbft_proto_rawDescOnce sync.Once
	file_chainedbft_proto_rawDescData = file_chainedbft_proto_rawDesc
)

func file_chainedbft_proto_rawDescGZIP() []byte {
	file_chainedbft_proto_rawDescOnce.Do(func() {
		file_chainedbft_proto_rawDescData = protoimpl.X.CompressGZIP(file_chainedbft_proto_rawDescData)
	})
	return file_chainedbft_proto_rawDescData
}

var file_chainedbft_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chainedbft_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_chainedbft_proto_goTypes = []interface{}{
	(MsgType)(0),                // 0: chainedbftpb.MsgType
	(*QuorumCertSignature)(nil), // 1: chainedbftpb.QuorumCertSignature
	(*ProposalMsg)(nil),         // 2: chainedbftpb.ProposalMsg
	(*VoteMsg)(nil),             // 3: chainedbftpb.VoteMsg
}
var file_chainedbft_proto_depIdxs = []int32{
	1, // 0: chainedbftpb.ProposalMsg.Sig:type_name -> chainedbftpb.QuorumCertSignature
	1, // 1: chainedbftpb.VoteMsg.sigs:type_name -> chainedbftpb.QuorumCertSignature
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_chainedbft_proto_init() }
func file_chainedbft_proto_init() {
	if File_chainedbft_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chainedbft_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuorumCertSignature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chainedbft_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProposalMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chainedbft_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoteMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chainedbft_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chainedbft_proto_goTypes,
		DependencyIndexes: file_chainedbft_proto_depIdxs,
		EnumInfos:         file_chainedbft_proto_enumTypes,
		MessageInfos:      file_chainedbft_proto_msgTypes,
	}.Build()
	File_chainedbft_proto = out.File
	file_chainedbft_proto_rawDesc = nil
	file_chainedbft_proto_goTypes = nil
	file_chainedbft_proto_depIdxs = nil
}
