# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/docs/**'
      - '**/README.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/docs/**'
      - '**/README.md'

#defaults:
#  run:
#    working-directory: 'example/poa'

jobs:

  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23.0

    - name: Run Makefile check-mod-tidy
      run: make check-mod-tidy

    - name: Build poa
      run: cd example/poa && go build -race -v

  test-single-node:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23.0

    - name: Test Single Node
      run: make test
